services:
  postgres:
    image: postgres:15-alpine
    container_name: event-system-db
    environment:
      POSTGRES_DB: event_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: event-system-api
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/event_system?schema=public
      - NODE_ENV=development
    depends_on:
      - postgres

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: event-system-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

volumes:
  postgres_data: 